import { useEffect, useState } from 'react';
import { api, type Shelter } from '../api/client';

type Advisory = { identifier:string; sent:string; status:string; msgType:string; source:string; scope:string; info:{ category:string; event:string; urgency:string; severity:string; certainty:string; headline:string; description:string; instruction:string; area:{ areaDesc:string }[] }[] };
export default function EmergencyHubPage(){
  const [shelters,setShelters]=useState<Shelter[]>([]); const [agencies,setAgencies]=useState<any[]>([]);
  const [message,setMessage]=useState('Flash flood threat advisory: move to designated safe shelter and follow official responder instructions.');
  const [settlement,setSettlement]=useState('Joshimath'); const [causalReason,setCausalReason]=useState('Risk drivers require confirmation from current rainfall, soil-saturation, slope and river-gauge telemetry.'); const [route,setRoute]=useState('Follow locally verified uphill evacuation route to the nearest open shelter.');
  const [arrival,setArrival]=useState('Unvalidated; check official gauges'); const [sent,setSent]=useState(false);
  useEffect(()=>{Promise.all([api.get('/api/logistics/shelters'),api.get('/api/logistics/agencies')]).then(([a,b])=>{setShelters(a.data);setAgencies(b.data)}).catch(()=>undefined)},[]);
  const advisory = ():Advisory => ({identifier:`geonexora-${Date.now()}`,sent:new Date().toISOString(),status:'Exercise',msgType:'Alert',source:'GeoNexora demonstration console',scope:'Public',info:[{category:'Met',event:'Flash flood threat advisory',urgency:'Immediate',severity:'Severe',certainty:'Possible',headline:`Flash flood advisory for ${settlement}`,description:`${message} Causal reason: ${causalReason}`,instruction:`Settlement: ${settlement}. Causal reason: ${causalReason} Route/shelter: ${route} Estimated wave arrival: ${arrival}.`,area:[{areaDesc:settlement}]}]});
  const download = (format:'json'|'xml') => { const data=advisory(); const content=format==='json'?JSON.stringify(data,null,2):`<?xml version="1.0" encoding="UTF-8"?>\n<alert xmlns="urn:oasis:names:tc:emergency:cap:1.2"><identifier>${escapeXml(data.identifier)}</identifier><sender>geonexora-demo</sender><sent>${data.sent}</sent><status>Exercise</status><msgType>Alert</msgType><scope>Public</scope><info><category>Met</category><event>Flash flood threat advisory</event><urgency>Immediate</urgency><severity>Severe</severity><certainty>Possible</certainty><headline>${escapeXml(`Flash flood advisory for ${settlement}`)}</headline><description>${escapeXml(`${message} Causal reason: ${causalReason}`)}</description><instruction>${escapeXml(`Settlement: ${settlement}. Causal reason: ${causalReason}. ${route} Estimated wave arrival: ${arrival}`)}</instruction><area><areaDesc>${escapeXml(settlement)}</areaDesc></area></info></alert>`; const blob=new Blob([content],{type:format==='json'?'application/json':'application/xml'}); const url=URL.createObjectURL(blob); const a=document.createElement('a');a.href=url;a.download=`geonexora-cap-advisory.${format}`;a.click();URL.revokeObjectURL(url); };
  const dispatch=async()=>{await api.post('/api/logistics/broadcast',{targets:[settlement],channels:['SMS','WhatsApp (simulation)','Siren','Radio'],message:`${message}\nCausal reason: ${causalReason}\nRoute: ${route}\nEstimated wave arrival: ${arrival}`});setSent(true)};
  return <div><div className="page-head"><div><span className="eyebrow">EMERGENCY HUB</span><h1>Relief & Dispatch</h1><p>Shelter capacity, responder hotlines and commander-controlled advisory dispatch.</p></div></div><div className="emergency-grid"><section className="panel"><span>SHELTER LOGISTICS</span><h2>Available relief capacity</h2><div className="shelters">{shelters.map(s=>{const available=Math.max(0,s.max_capacity-s.occupied_beds);const pct=s.max_capacity?Math.min(100,s.occupied_beds/s.max_capacity*100):0;return <div className="shelter" key={s.id}><div><b>{s.name}</b><small>{s.occupied_beds}/{s.max_capacity} occupied · {available} available · {s.food_days} days food · {s.medical_staff} medical staff</small><div style={{height:6,background:'#e5e7eb',borderRadius:6,marginTop:7,overflow:'hidden'}}><div style={{height:'100%',width:`${pct}%`,background:pct>90?'#c53030':'#2b8a5b'}}/></div></div><strong className={s.generator_online?'ok':'warn'}>{s.generator_online?'GENERATOR OK':'GENERATOR OFF'}</strong></div>})}</div></section><section className="panel"><span>CAP-COMPATIBLE ADVISORY EXPORT</span><h2>Tactical commander advisory</h2><label>Target ward / settlement<select value={settlement} onChange={e=>setSettlement(e.target.value)}><option>Joshimath</option><option>Pipalkoti</option><option>Chamoli</option><option>Govindghat</option></select></label><label>Commander message<textarea value={message} onChange={e=>setMessage(e.target.value)}/></label><label>Explainable causal reason<textarea value={causalReason} onChange={e=>setCausalReason(e.target.value)}/></label><label>Safe route and shelter instruction<textarea value={route} onChange={e=>setRoute(e.target.value)}/></label><label>Estimated wave arrival<input value={arrival} onChange={e=>setArrival(e.target.value)}/></label><div className="chips"><span>SMS simulation</span><span>WhatsApp simulation</span><span>Siren</span><span>Radio</span></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:12}}><button onClick={()=>download('json')}>Export CAP JSON</button><button onClick={()=>download('xml')}>Export CAP XML</button><button className="primary danger" onClick={dispatch}>Simulate broadcast</button></div>{sent&&<p className="success">Broadcast simulation request submitted to backend. No real SMS/WhatsApp message was sent unless an external provider is configured.</p>}<h3>24/7 agency directory</h3>{agencies.map(a=><div className="agency" key={a.id}><b>{a.agency}</b><span>{a.hotline}</span></div>)}</section></div></div>
}
function escapeXml(value:string){return value.replace(/[<>&'\"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[c]??c));}
