import { useEffect, useMemo, useState } from 'react';
import { api } from '../api/client';

type ReplayStep = { step:number; time_label:string; upstream_flow_rate:number; seismic_acoustic_trigger:number; river_level_spike:number; soil_saturation:number; threat_score:number; threat_level:string; data_status:string };
type ReplayResponse = { event:string; data_status:string; source_note:string; detection_lead_time_claim:number|null; steps:ReplayStep[] };
export default function HistoricalAnalyticsPage() {
  const [rows, setRows] = useState<any[]>([]); const [replay, setReplay] = useState<ReplayResponse|null>(null);
  const [index, setIndex] = useState(0); const [playing, setPlaying] = useState(false); const [speed, setSpeed] = useState(1); const [error, setError] = useState('');
  useEffect(() => { api.get('/api/analytics/incidents').then(r=>setRows(r.data)).catch(()=>setError('Incident archive could not be loaded.')); api.get<ReplayResponse>('/api/v1/analytics/replay/chamoli-2021').then(r=>setReplay(r.data)).catch(()=>setError('Replay endpoint could not be loaded.')); }, []);
  useEffect(() => { if (!playing || !replay) return; const timer = window.setInterval(() => setIndex(i => { if (i >= replay.steps.length - 1) { setPlaying(false); return i; } return i + 1; }), 1600 / speed); return () => window.clearInterval(timer); }, [playing, speed, replay]);
  const step = useMemo(() => replay?.steps[index], [replay,index]);
  const threatColor = step?.threat_level === 'Critical' ? '#c53030' : step?.threat_level === 'High' ? '#dd6b20' : step?.threat_level === 'Moderate' ? '#b7791f' : '#22845a';
  return <div><div className="page-head"><div><span className="eyebrow">HISTORICAL ARCHIVE</span><h1>Disaster Incident Simulator & Replay</h1><p>Explore a reconstructed timeline for the Chamoli 2021 rock–ice avalanche and debris-flow disaster.</p></div><a className="primary" href={`${api.defaults.baseURL || ''}/api/analytics/incidents.csv`}>Export CSV</a></div>
    {error && <p role="alert">{error}</p>}
    <section className="panel" style={{ marginBottom: 20 }}><div style={{ display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap' }}><div><span className="eyebrow">INCIDENT REPLAY</span><h2>{replay?.event ?? 'Loading historical replay…'}</h2></div><span style={{ alignSelf:'start', background:'#fff0cf', color:'#7a4b00', padding:'7px 10px', borderRadius:8, fontWeight:700 }}>RECONSTRUCTED DEMO DATA</span></div>
      {step && <><div style={{ display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(145px,1fr))',gap:12,margin:'18px 0' }}>
        <Metric label="Timeline" value={step.time_label}/><Metric label="Upstream flow" value={`${step.upstream_flow_rate} m³/s`}/><Metric label="Seismic/acoustic index" value={`${step.seismic_acoustic_trigger}/100`}/><Metric label="River level spike" value={`${step.river_level_spike.toFixed(1)} m`}/><Metric label="Soil saturation" value={`${step.soil_saturation}%`}/><Metric label="Threat level" value={step.threat_level} color={threatColor}/>
      </div><div style={{ height:10,background:'#e7edf0',borderRadius:10,overflow:'hidden' }}><div style={{ height:'100%',width:`${step.threat_score*100}%`,background:threatColor,transition:'width .3s' }}/></div><p>Illustrative threat index: <b>{Math.round(step.threat_score*100)} / 100</b></p>
      <input aria-label="Replay timeline" type="range" min={0} max={Math.max(0,(replay?.steps.length??1)-1)} value={index} onChange={e=>{setPlaying(false);setIndex(Number(e.target.value));}} style={{ width:'100%' }}/><div style={{ display:'flex',gap:8,flexWrap:'wrap',alignItems:'center' }}><button className="primary" onClick={()=>setPlaying(true)} disabled={playing || index >= (replay?.steps.length ?? 1) - 1}>Play</button><button onClick={()=>setPlaying(false)}>Pause</button><button onClick={()=>{setPlaying(false);setIndex(i=>Math.min(i+1,(replay?.steps.length??1)-1));}}>Step Forward</button><button onClick={()=>{setPlaying(false);setIndex(0);}}>Reset</button><label>Speed <select value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={1}>1×</option><option value={5}>5×</option><option value={10}>10×</option></select></label></div>
      <p style={{ marginTop:16,fontSize:13 }}>{replay?.data_status}. {replay?.source_note}</p><div style={{ border:'1px solid #e4a23a',background:'#fff9e8',padding:12,borderRadius:10 }}><b>Historical claim status:</b> “54-minute advance warning” is not verified by the data supplied with this project and is intentionally not presented as a proven result. Add authoritative timestamps and documented detection evidence before displaying that claim.</div></>}
    </section>
    <div className="panel"><h2>Incident records</h2><div className="history">{rows.map(x=><div key={x.id} className="history-row"><b>{x.title}</b><span>{x.location}</span><span>{new Date(x.date).toLocaleDateString()}</span><strong>{x.severity}</strong><span>{x.fatalities} fatalities · {x.rainfall_mm} mm</span></div>)}</div></div>
  </div>;
}
function Metric({label,value,color}:{label:string;value:string;color?:string}) { return <div style={{padding:14,border:'1px solid #dce4e8',borderRadius:10}}><small style={{display:'block',opacity:.7,marginBottom:8}}>{label}</small><strong style={{color}}>{value}</strong></div>; }
